<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitRunTravisYml
{
    public static $prefixLengthsPsr4 = array (
        'K' => 
        array (
            'Ktomk\\Pipelines\\' => 16,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Ktomk\\Pipelines\\' => 
        array (
            0 => __DIR__ . '/..' . '/ktomk/pipelines',
        ),
    );

    public static $prefixesPsr0 = array (
        'S' => 
        array (
            'Symfony\\Component\\Yaml\\' => 
            array (
                0 => __DIR__ . '/..' . '/ktomk/symfony-yaml',
            ),
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitRunTravisYml::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitRunTravisYml::$prefixDirsPsr4;
            $loader->prefixesPsr0 = ComposerStaticInitRunTravisYml::$prefixesPsr0;

        }, null, ClassLoader::class);
    }
}
