name: run .travis.yml
author: Tom Klingenberg <https://github.com/ktomk>
description: Run `.travis.yml` Stages/Scripts (Travis-CI) as Github Action (Github)

branding:
  color: yellow
  icon: shuffle

inputs:
  file:
    description: |
      Path to `.travis.yml` file. Leave empty / unset for default
      `.travis.yml`. Relative to project root. Overrides the
      `TRAVIS_YAML_FILE` environment variable if non-empty.
    default: ''
    required: false

  stages:
    description: |
      Space separated list of stages to run. Leave empty
      / unset to run all custom stage scripts.
    default: ''
    required: true

  allow_failure:
    description: |
      Allow the .travis.yml build to fail. Possible values are
      `true` and `false`. Overrides the `TRAVIS_ALLOW_FAILURE`
      environment variable if set.
    default: ''
    required: false

outputs:
  test_result:
    description: |
      Outcome of `TRAVIS_TEST_RESULT`, either `0` if all commands
      in the `script` section have exited with zero or `1`
      otherwise.
    value: ${{ steps.travis-build-sh.outputs.exit-status }}

  conclusion:
    description: |
      The result of the .travis.yml build after `allow_failure`
      / `TRAVIS_ALLOW_FAILURE` is applied. Possible values
      are `success` or `failure`.
    value: ${{ steps.travis-build-sh.outputs.conclusion }}

  outcome:
    description: |
      The result of the .travis.yml build before `allow_failure`
      / `TRAVIS_ALLOW_FAILURE` is applied. Possible values
      are `success` or `failure`.
    value: ${{ steps.travis-build-sh.outputs.outcome }}

runs:
  using: composite

  steps:
    - id: travis-build-sh
      shell: bash
      run: |
        : [1/3] action binding
        . "$GITHUB_ACTION_PATH"/lib/binding.sh
        : [2/3] register action
        reg  allow_failure      "${{ inputs.allow_failure }}"
        reg  event_name         "${{ github.event_name }}"
        reg  event_number       "${{ github.event.number }}"
        reg  repository         "${{ github.repository }}"
        reg  travis_file        "${{ inputs.file }}"
        reg  travis_stages      "${{ inputs.stages }}"
        : [3/3] action
        . "$GITHUB_ACTION_PATH"/lib/action.sh
