name: run .travis.yml
author: Tom Klingenberg <https://github.com/ktomk>
description: Run `.travis.yml` Stages/Scripts (Travis-CI) as Github Action (Github)

branding:
  color: yellow
  icon: shuffle

inputs:
  file:
    description: |
      Path to `.travis.yml` file. Leave empty / unset for default
      `.travis.yml`. Relative to project root. Overrides the
      `TRAVIS_YAML_FILE` environment variable if non-empty.
    default: ''
    required: false

  stages:
    description: |
      Space separated list of stages to run. Leave empty
      / unset to run all custom stage scripts.
    default: ''
    required: true

  allow_failure:
    description: |
      Allow the .travis.yml build to fail. Possible values are
      `true` and `false`. Overrides the `TRAVIS_ALLOW_FAILURE`
      environment variable if set.
    default: ''
    required: false

runs:
  using: composite

  steps:
    - shell: bash
      run: |
        : [1/3] action binding
        . "$GITHUB_ACTION_PATH"/lib/binding.sh
        : [2/3] register action
        reg  allow_failure      "${{ inputs.allow_failure }}"
        reg  event_name         "${{ github.event_name }}"
        reg  event_number       "${{ github.event.number }}"
        reg  repository         "${{ github.repository }}"
        reg  travis_file        "${{ inputs.file }}"
        reg  travis_stages      "${{ inputs.stages }}"
        : [3/3] action
        . "$GITHUB_ACTION_PATH"/lib/action.sh
